apiVersion: v1
kind: Secret
metadata:
  name: authsrv-private-key
  labels:
    name: authsrv-private-key
    app: authsrv
  namespace: authsrv-namespace
data:
  private: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JSGNBZ0VCQkVJQk5ZQ3pZbWNSUXZWMG1vcjFLdG1JajE1d3F2RktCc1ZOL2NnSGZFR3ZtMnVUNXVKYmpUcVMKVks4VWo4TWlNUFFpWG9wQ3Z2bUVjME9mbEg5QUxLVEdQbGFnQndZRks0RUVBQ09oZ1lrRGdZWUFCQUVDN2FiNwpxZW0zMG9ZR1J5cGh4TEVWZ1BFS05PbjlZT05aNWg2bDZUc05WZy9YK2Q1enIvOVNCTC9rc3FCaVZZRVVrekM4CjFFNUxDRjFBS0FZWlZ2VFFSQUVvV0ErVjcxMklmNk01QWhlcmRFczNudDg3VFh5c3JRaXRTSDh2bWN3dGdjc0YKREsxQW1ZSVl2YVAySkxWS2xJdU1xVUhDZ2YveDRQVTNQN2l6ZXl5L213PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

