apiVersion: v1
kind: Service
metadata:
  name: authsrv-service
  namespace: authsrv-namespace
  labels:
    app: authsrv
spec:
  selector:
    app: authsrv
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
